# Generated by Django 3.0.8 on 2020-07-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='invalid_trigger',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='invalid_trigger'),
        ),
        migrations.AlterField(
            model_name='values',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='values',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='values',
            name='pick_first',
            field=models.BooleanField(blank=True, verbose_name='pick_first'),
        ),
        migrations.AlterField(
            model_name='values',
            name='reuse',
            field=models.BooleanField(blank=True, verbose_name='reuse'),
        ),
        migrations.AlterField(
            model_name='values',
            name='support_multiple',
            field=models.BooleanField(blank=True, null=True, verbose_name='support_multiple'),
        ),
        migrations.AlterField(
            model_name='values',
            name='supported_values',
            field=models.TextField(blank=True, max_length=150, verbose_name='supported_values'),
        ),
        migrations.AlterField(
            model_name='values',
            name='type',
            field=models.TextField(blank=True, max_length=150, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='values',
            name='validation_parser',
            field=models.CharField(blank=True, max_length=150, verbose_name='validation_parser'),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.TextField(blank=True, max_length=150, verbose_name='values'),
        ),
    ]
