# Generated by Django 3.0.8 on 2020-07-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200710_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='reuse',
            field=models.BooleanField(blank=True, null=True, verbose_name='reuse'),
        ),
    ]
