# Generated by Django 3.0.8 on 2020-07-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20200710_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='pick_first',
            field=models.BooleanField(blank=True, null=True, verbose_name='pick_first'),
        ),
        migrations.AlterField(
            model_name='values',
            name='supported_values',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='supported_values'),
        ),
        migrations.AlterField(
            model_name='values',
            name='type',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='values',
            name='validation_parser',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='validation_parser'),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='values'),
        ),
    ]
