# Generated by Django 3.0.8 on 2020-07-10 23:17

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20200710_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='supported_values',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=2000, null=True, size=10, verbose_name='supported_values'),
        ),
    ]
