# Generated by Django 3.0.8 on 2020-07-11 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20200710_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='supported_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, max_length=2000, null=True, size=10, verbose_name='supported_values'),
        ),
        migrations.AlterField(
            model_name='values',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, max_length=2000, null=True, size=None, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='values',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, max_length=2000, null=True, size=None, verbose_name='values'),
        ),
    ]
