# Generated by Django 3.0.8 on 2020-07-11 06:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20200711_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='supported_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, max_length=2000, null=True, size=None, verbose_name='supported_values'),
        ),
    ]
