# Generated by Django 3.0.8 on 2020-07-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20200711_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='support_multiple',
        ),
        migrations.RemoveField(
            model_name='values',
            name='supported_values',
        ),
        migrations.RemoveField(
            model_name='values',
            name='type',
        ),
    ]
