# Generated by Django 3.0.8 on 2020-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20200711_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='values',
        ),
        migrations.AddField(
            model_name='values',
            name='support_multiple',
            field=models.BooleanField(blank=True, null=True, verbose_name='support_multiple'),
        ),
    ]
