# Generated by Django 3.0.8 on 2020-07-11 06:56

import django.contrib.postgres.fields
from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_auto_20200711_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_mysql.models.JSONField(default=dict), blank=True, null=True, size=None, verbose_name='values'),
        ),
    ]
