# Generated by Django 3.0.8 on 2020-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0016_auto_20200711_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='constraint',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Constraint'),
        ),
        migrations.AddField(
            model_name='values',
            name='var_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='var_name'),
        ),
    ]
